# -*- coding: utf-8 -*-
"""EjerciciosPythonU.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PjjilsXT38WuZxNVRy63LKa2QeTrzB-i
"""

print('Hola mundo!')

nombre = input ("introduce tu nombre ")
print ("¡Hola "  + nombre+ "¡" )

imc =24
peso = float (input("ingrese su peso "))
altura = float (input("ingrese su altura "))
imc = round(float(peso)/float(altura)**2,2)
print("Tu índice de masa corporal es " + str(imc))

n = int(input("Introduce un número entero: "))
suma = n * (n + 1) / 2
print("La suma de los primeros números enteros desde 1 hasta " + str(n) + " es " + str(suma))

from datetime import datetime, timedelta
from time import strftime

now = datetime.now()
now_less_5hours=now - timedelta(hours=5)

current_time = now_less_5hours.strftime("%H:%M:%S")
print("Current Time =", current_time)
print(now_less_5hours.isoweekday())

dia=now_less_5hours.isoweekday()

if (dia == 2 or dia==4):
  print("hay clase")
else:
  print("no hay clase")

password="micheltovarymariaforero"
contraseña=input("ingrese su contrseña: ")

if (contraseña.lower()==password.lower()):
        print("contraseña correcta")
   
else:
     
       print("contraseña incorrecta")